#numpy    Problem 1 — Basic Statistics


Create a NumPy array:


In [5]:
import numpy as np
arr=np.array([45,67,89,32,76,90,55])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

454
64.85714285714286
90
32


Problem 2 — Condition + Filtering

In [11]:
arr = np.array([12, 25, 7, 30, 18, 45, 9, 50])
 
print(arr[arr>20])


[25 30 45 50]


 Problem 3 🟢 

In [12]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[arr<25])

[10 15 20]


Problem 4 🟢

In [14]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr>15]*2)

[40 50]


Problem 5 🟢

In [17]:
arr = np.array([12, 25, 8, 40, 15, 33, 7])
print(arr[arr%2==0])


[12  8 40]


Problem 6 🟢

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
(arr[arr>30])=100
 

[ 10  20 100 100 100]


Problem 7 🟢

In [24]:
arr = np.array([10, 20, 30, 40, 50])
np.sum(arr[arr>20])
np.mean(arr[arr>20])

np.float64(40.0)

Problem 8 🟢

In [26]:
arr = np.array([5, 12, 18, 25, 30, 7])
arr[(arr >= 10) & (arr <= 25)]

array([12, 18, 25])

Problem 9 🟢

In [31]:
arr = np.array([10, 20, 30, 40, 50])
print(arr**2)

[ 100  400  900 1600 2500]


Problem 10 🟢

In [35]:
arr = np.array([15, 22, 8, 35, 40, 12])
print(np.max(arr[arr>20]))

40


Mini Assignment: Student Marks Analysis

In [54]:
import numpy as np

marks = np.array([45, 67, 89, 32, 76, 90, 55, 82, 38, 95])

print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(marks[marks>=70])
print(marks[marks<50])
print(marks[marks<50]+5)
marks[marks < 50] = marks[marks < 50] + 5
print(marks)
print(np.max(marks))
print(np.mean(marks[marks>80]))
 


669
66.9
95
32
[89 76 90 82 95]
[45 32 38]
[50 37 43]
[50 67 89 37 76 90 55 82 43 95]
95
89.0
