Problem 1 — Create a NumPy Array     

Create a NumPy array containing the numbers 5, 10, 15, 20, 25 and print the array.


In [1]:
import numpy as np
arr=np.array([5,10,15,20,25])
print(arr)

[ 5 10 15 20 25]


Practice 2 — Check Array Properties          

For the array [10, 20, 30, 40, 50], print its number of dimensions, shape, and size.

In [4]:
import numpy as np 
arr=np.array([10,20,30,40,50])
print(arr.size)
print(arr) #NORMAL PRINT 
print(arr.ndim) # DIMENSION
print(arr.shape) #SHAPE

5
[10 20 30 40 50]
1
(5,)


Practice 3 — 2D Array   

Create a 2D NumPy array with 2 rows and 3 columns:


In [7]:
import numpy as np
arr=np.array([
    [10,20,30],
    [40,50,60]
])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[10 20 30]
 [40 50 60]]
2
(2, 3)
6


Practice 4 — Array Indexing

In [8]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[-1])


10
30
50


Practice 5 — 2D Array Indexing

In [11]:
import numpy as np
arr=np.array([
    [10,20,30],
    [40,50,60]
])
print(arr[0] [0])
print(arr[1] [1])
print(arr[1][2])


10
50
60


Practice 6 — Slicing

In [18]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0:3])
print(arr[3:5])
print(arr[1:-1])


[10 20 30]
[40 50]
[20 30 40]


Practice 7 — Array Operations


Every element + 5

Every element × 2

Every element ÷ 10

Every element − 5

In [20]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr+5)
print(arr*2)
print(arr/10)
print(arr-5)

[15 25 35 45 55]
[ 20  40  60  80 100]
[1. 2. 3. 4. 5.]
[ 5 15 25 35 45]


Practice 8 — Broadcasting

In [21]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])

print(a+b)


[11 22 33 44 55]


Practice 9 — Broadcasting with Scalar

In [22]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
print(arr*3+2)


[17 32 47 62 77]


Practice 10 — 2D Array Operations

In [23]:
import numpy as np
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr+10)

[[20 30 40]
 [50 60 70]]


Day 5 — NumPy Mini Assignment

In [52]:
import numpy as np
#creating numpy array
arr = np.array([
    ["Madhu", 80],
    ["Punam", 70],
    ["Rahul", 90],
    ["Amit", 60],
    ["Priya", 85]
])
#basic operations
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

#indexing
print(arr[0])
print(arr[2])
print(arr[4])

#slicing
print(arr[0:3])
print(arr[3:5])

#bonus mark
marks = np.array([80, 70, 90, 60, 85])
print(marks+5)
#average
print(np.mean(marks))





[['Madhu' '80']
 ['Punam' '70']
 ['Rahul' '90']
 ['Amit' '60']
 ['Priya' '85']]
2
(5, 2)
10
['Madhu' '80']
['Rahul' '90']
['Priya' '85']
[['Madhu' '80']
 ['Punam' '70']
 ['Rahul' '90']]
[['Amit' '60']
 ['Priya' '85']]
[85 75 95 65 90]
77.0


Day 5 — NumPy Basics: COMPLETE ✅




# Day 05 — NumPy Basics

## Topics Covered
- NumPy arrays
- 1D and 2D arrays
- ndim, shape, size
- Indexing
- Slicing
- Array operations
- Broadcasting
- Mean / Average

## Practice
- 10 NumPy practice problems
- 1 Mini Assignment

## Key Learning
- np.array() → creates NumPy arrays
- ndim → number of dimensions
- shape → structure of array
- size → total number of elements
- Indexing → access elements
- Slicing → select a range of elements
- Broadcasting → operations across arrays/elements
- np.mean() → calculates average